[package]
name = "rust-calchist"
version = "0.1.0"
authors = ["Mike Garrity"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.41"
